#+title: Doom emacs configuration

* Setup
** Tangle Headers
#+begin_src elisp :tangle config.el
;; -*- lexical-binding: t -*-
#+end_src

#+begin_src elisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+end_src

Don't do init.el
# #+begin_src elisp :tangle "init.el" :comments no
# ;; -*- no-byte-compile: t; -*-
# #+end_src

* General look and feel
I like this theme as it has a lot of not washed out colors.
Week starts at monday here, despite what the Bible says.

#+begin_src elisp :tangle config.el
(setq doom-theme 'tsdh-dark
      display-line-numbers-type t
      calendar-week-start-day 1
      doom-font (font-spec :family "FiraCode Nerd Font" :size 15)
      )
#+end_src
* Org mode configuration
Org mode configuration

** Emacs start config
Open this and close at the end of org mode configuration
#+begin_src elisp :tangle config.el
(after! org
#+end_src

** org-mode dirs
#+begin_src elisp :tangle config.el
(setq org-directory "~/org/")
#+end_src
** look and feel
*** org-modern
#+begin_src elisp :tangle packages.el
(package! org-modern)
#+end_src
*** indent level
Indent each org mode level a bit more for a better overview
#+begin_src elisp :tangle config.el
(setq org-indent-indentation-per-level 4)
#+end_src
*** 'REVIEW' keyword
#+begin_src elisp :tangle config.el
(defun append-org-todo-keyword (new-keyword)
  "Append a NEW-KEYWORD to the first sequence in `org-todo-keywords`."
  (let ((current-keywords (car org-todo-keywords)))
    (when (eq (car current-keywords) 'sequence)
      (setq org-todo-keywords
            (cons (append current-keywords (list new-keyword))
                  (cdr org-todo-keywords))))))

;; Call the (function )
(append-org-todo-keyword "REVIEW")
#+end_src
*** Custom faces
#+begin_src elisp :tangle config.el
(setq org-todo-keyword-faces
      (append org-todo-keyword-faces
              '(("REVIEW" . (:foreground "light blue" :weight bold))
                ("DONE" . (:foreground "green" :weight bold :strike-through t)))))
(custom-set-faces '(org-drawer ((t (:foreground "grey" :weight bold :height: 1.3)))))
#+end_src
** Org ol-gnus
Add gnus support
#+begin_src elisp :tangle config.el
(add-to-list 'org-modules 'ol-gnus)
#+end_src
** Org-ql
This allows to index org-mode quickly. Might be a good alternative to org-agenda
#+begin_src elisp :tangle packages.el
(package! org-ql)
#+end_src
** Agenda
*** Agenda format
#+begin_src elisp :tangle config.el
(setq org-agenda-prefix-format
      '((agenda . "   %i %-12c%?-2t %-12s %-6e")  ; Agenda items: icon, category, time, and extra info, estimate
        (todo .   "   %i %-12:c %-12:t %s")   ; TODO items: icon, category, time (if any), and extra info
        (tags .   "   %i %-12:c %-12:t %s")   ; Tagged items: icon, category, time (if any), and extra info
        (search . "   %i %-12:c %s")))      ; Search results: icon, category, and extra info

#+end_src
*** Super agenda setup
#+begin_src elisp :tangle packages.el
(package! org-super-agenda)
#+end_src

#+begin_src elisp :tangle config.el
(add-hook 'org-agenda-mode-hook 'org-super-agenda-mode)
(setq org-super-agenda-groups
      '((:log t)  ; Automatically named "Log"
        (:name "Schedule"
         :time-grid t)
        (:name "Today"
         :scheduled today)
        (:habit t)
        (:name "Due today"
         :deadline today)
        (:name "Overdue"
         :deadline past)
        (:name "Due soon"
         :deadline future)
        (:name "Scheduled earlier"
         :scheduled past)
        )
      )
(custom-set-faces '(org-super-agenda-header ((t (:foreground "dark orange" :weight bold :height: 1.3)))))
(setq org-super-agenda-header-separator "\n---\n")
#+end_src

** Org mode configuration end
#+begin_src elisp :tangle config.el
)
#+end_src
* GnuPG
Use gnome GPG agent
#+begin_src elisp :tangle config.el
(after! gnus-agent
  (setq epg-pinentry-mode 'nil)
  )
#+end_src
* Rust
Don't continue comment on the next line when. This is annoying
#+begin_src elisp :tangle config.el
(setq-hook! 'rust-mode-hook comment-line-break-function nil)
#+end_src
* LSP-mode
Show types in lsp and allow for larger projects without being bothered all the time about it.

#+begin_src elisp :tangle config.el
(after! lsp-mode
  (setq lsp-inlay-hint-enable t
        lsp-file-watch-threshold 3000)
  )
#+end_src
* Indent bars
#+begin_src elisp :tangle config.el
(after! indent-bars
  (setq
   indent-bars-color '(highlight :face-bg t :blend 0.15)
   indent-bars-pattern "."
   indent-bars-width-frac 0.1
   indent-bars-pad-frac 0.1
   indent-bars-zigzag nil
   indent-bars-color-by-depth '(:regexp "outline-\\([0-9]+\\)" :blend 1) ; blend=1: blend with BG only
   indent-bars-highlight-current-depth '(:blend 0.5) ; pump up the BG blend on current
   indent-bars-display-on-blank-lines t)
  )
#+end_src
* AI / LLM
Set up LLM packages
** Ellama
#+begin_src elisp :tangle packages.el
(package! ellama)
#+end_src

#+begin_src elisp :tangle config.el
(after! ellama
  (setopt ellama-keymap-prefix "C-c z")  ;; keymap for all ellama functions
  (setopt ellama-language "English")
  (require 'llm-openai)
  (setopt ellama-provider
	  (make-llm-ollama
	   ;; this model should be pulled to use it
	   ;; value should be the same as you print in terminal during pull
	   :chat-model "qwen2.5:14b"
	   :embedding-model "qwen2.5:14b"
	   ))
  (setq llm-warn-on-nonfree nil
        ellama-providers
        '(("gpt4o" . (make-llm-openai
                      :key (getenv "OPENAI_API_KEY")
                      :chat-model "gpt-4o"
                      ))
          ("deepseek-chat" . (make-llm-openai-compatible
                              :key (getenv "DEEPSEEK_API_KEY")
                              :url "https://api.deepseek.com/"
                              :chat-model "deepseek-chat"))
          )
        )
  )
#+end_src
** GPTEL
#+begin_src elisp :tangle packages.el
(package! gptel)
#+end_src

#+begin_src elisp :tangle config.el
(defun get-ollama-models ()
  "Fetch the list of installed Ollama models."
  (let* ((output (shell-command-to-string "ollama list"))
         (lines (split-string output "\n" t))
         models)
    (dolist (line (cdr lines))  ; Skip the first line
      (when (string-match "^\\([^[:space:]]+\\)" line)
        (push (match-string 1 line) models)))
    (nreverse models)))

(use-package! gptel
  :config
  (setq! gptel-api-key (getenv "OPENAI_API_KEY")
         gptel-default-mode 'org-mode
         gptel-model "gpt-4o")
  ;; DeepSeek offers an OpenAI compatible API
  (gptel-make-openai "DeepSeek"       ;Any name you want
    :host "api.deepseek.com"
    :endpoint "/chat/completions"
    :stream t
    :key (getenv "DEEPSEEK_API_KEY")
    :models '("deepseek-chat" "deepseek-coder"))
  (gptel-make-anthropic "Claude"          ;Any name you want
    :stream t                             ;Streaming responses
    :key (getenv "ANTHROPIC_API_KEY"))
  (gptel-make-ollama "Ollama"             ;Any name of your choosing
    :host "localhost:11434"               ;Where it's running
    :stream t                             ;Stream responses
    :models (get-ollama-models))          ;List of models
  (gptel-make-openai "llama-cpp"          ;Any name
    :stream t                             ;Stream responses
    :protocol "http"
    :host "localhost:8081"                ;Llama.cpp server location
    :models '("qwen2.5-coder"))                    ;Any names, doesn't matter for Llama
  )
#+end_src
** Aider
#+begin_src elisp :tangle packages.el
(package! aider
  :recipe (:host github :repo "tninja/aider.el" :files ("aider.el"))
  :pin "fe6148c0648f07293a047d1c687944d33c40f4e4")
#+end_src

Add path to include aider installed from PIP
#+begin_src elisp :tangle config.el
(let ((local-bin (expand-file-name "~/.local/bin")))
  (setq exec-path (append exec-path (list local-bin)))
  (setenv "PATH" (concat local-bin path-separator (getenv "PATH"))))
#+end_src
* Kconfig mode
Edit Kconfig like a pro
#+begin_src elisp :tangle packages.el
(package! kconfig-mode
  :recipe (:host github :repo "delaanthonio/kconfig-mode")
  :pin "cd87b71c8c1739d026645ece0bbd20055a7a2d4a")
#+end_src
